insert into user values (1001, sysdate(), 'Guille')
insert into user values (1002, sysdate(), 'Elvira')
insert into user values (1003, sysdate(), 'Alejandro')
insert into post values (10001, 'Mi primer post', sysdate(), 'Prueba', 1001)
insert into post values (10002, 'Mi segundo post', sysdate(), 'Prueba 2', 1001)
